version: '3.8'

services:
  tuna-data:
    image: postgres:latest
    container_name: book_store_ctn
    restart: always
    environment:
      POSTGRES_USER: book-store-admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: book_store
    ports:
      - "5433:5432"
    volumes:
      - book_store:/var/lib/postgresql/data

volumes:
  book_store: